version: '3.8'

services:
  node1:
    environment:
      - SERVER_PORT=4000
      - MY_NAME=node1
      - MY_HOST=node1
    build: .
    networks:
      - default

  node2:
    environment:
      - SERVER_PORT=4001
      - MY_NAME=node2
      - MY_HOST=node2
    build: .
    networks:
      - default

  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379
    networks:
      - default

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80
    depends_on:
      - node1
      - node2
    networks:
      - default

networks:
  default: